// export { invokeHttpsCallable } from './invokeHttpsCallable'
// export { destroyRoom } from './destroyRoom'
// export { createRoom } from './createRoom'
/* c8 ignore next 8 */
export { searchByUserName } from './searchByUserName'
export { updateUserProfile } from './updateUserProfile'
export { getUserByUid } from './getUserByUid'
export { deleteUser } from './deleteUser'
export { deleteFriend } from './deleteFriend'
export { requestToBecomeFriend } from './requestToBecomeFriend'
export { acceptFriendRequest } from './acceptFriendRequest'
export { cancelFriendRequest } from './cancelFriendRequest'
