export { getCurrentUser } from './getCurrentUser'
export { getToken } from './getToken'
export { loginWithEmailAndPassword } from './loginWithEmailAndPassword'
export { loginWithGoogle } from './loginWithGoogle'
export { logout } from './logout'
export { onAuthStateChanged } from './onAuthStateChanged'
export { registerWithEmailAndPassword } from './registerWithEmailAndPassword'
export { sendEmailVerification } from './sendEmailVerification'
